### ISSUE TITLE
Using with cargo-local-registry

### ISSUE THREAD

**Issue by metaclips** [d-e-s-o/cargo-http-registry#2]
Hello, is it feasible to use this implementation with [cargo local registry](https://crates.io/crates/cargo-local-registry) I would love to sync dependencies before publishing locally.

**Comment by d-e-s-o** [comment]
Probably. I recommend trying it out.

**Comment by metaclips** [comment]
Seem how `cargo local registry` store indexes is totally different, `cargo-http-registry` stores both indexes and `.crate` files in same path

**Comment by metaclips** [comment]
Hello @d-e-s-o I think having the path structure will make `cargo-http-registry` compatible with `cargo-local-registry`, what do you think.
> parent_path
>> index_path
>> *.crate

**Comment by d-e-s-o** [comment]
I don't recall exactly what `cargo-local-registry` does. If you've tried it out and it works, feel free to create a pull request and we can change the layout.

**Comment by metaclips** [comment]
`cargo-local-registry` fetches library dependencies from crates.io and then stores them to our local filesystem thereby updating our local registry. The architecture `cargo-local-registry` uses to store indexes and .crate files is as stated in my last post. 
If we could make `cargo-local-registry` fetch dependencies from crates.io and then `cargo-http-registry` add packages that we published to our local registry, this will make a full fledged cargo server.

**Comment by d-e-s-o** [comment]
Pull request got merged. Thanks for your contribution!

**Comment by d-e-s-o** [comment]
So that turned out to not work as we intended it to. @metaclips can you please provide steps on how to test that it works with `cargo-local-registry` for you?

**Comment by metaclips** [comment]
> So that turned out to not work as we intended it to. @metaclips can you please provide steps on how to test that it works with `cargo-local-registry` for you?

Here's how I use it.
I start cargo-local-registry on folder `vendor`
```
cargo-http-registry ~/vendor  --addr="127.0.0.1:3333"
```
then I create a cargo/.config file in the `parent path` of my `crate or library` bash command which you can run on your crate below
```bash
mkdir .cargo && touch .cargo/config
echo -n $'[registries]\nmy-registry = { index = "http://127.0.0.1:3333/git" }\n\n[registry]\ndefault = "my-registry"\n\n[net]\ngit-fetch-with-cli = true\n\n#' > .cargo/config
```
Then I run `cargo-local-registry to help download my crates dependencies from crates.io` and pipe its config to the .cargo/config file.

```bash
cargo local-registry --sync Cargo.lock ~/vendor --no-delete >> ~/my_crate/.cargo/config
```

Note the `--no-delete` which indicates it shouldn't delete the `~/vendor` folder contents.
We should be able to call `cargo package or publish` after this.

**Comment by d-e-s-o** [comment]
For the steps you describe, I don't see how it matters whether there is an `index/` directory or not. They go through irrespectively from what I can tell. `cargo publish` would just pull from `~/vendor` and doesn't care about the registry and its contents. I suspect you just couldn't later build a project consuming the library *and* its dependencies solely through the registry.

**Comment by d-e-s-o** [comment]
That being said, I reworked things to use a symlink instead, which should cater to this case: https://github.com/d-e-s-o/cargo-http-registry/tree/topic/symlink

Can you please try it out and see if it works for you?

**Comment by metaclips** [comment]
> That being said, I reworked things to use a symlink instead, which should cater to this case: https://github.com/d-e-s-o/cargo-http-registry/tree/topic/symlink
> 
> Can you please try it out and see if it works for you?

It doesn't work for me. Here's where/how it fails on my end. 
I have two crates, `A, B, and C`. `Crate C is dependent on B and A`, when we upload/publish crate A and B, their indexes is stored out of the `index` path ( `cargo-local-registry` stores all indexes in the index path which we should follow suit so that its config can work for us ).

cargo .config is stated as 
```
[registries]
my-registry = { index = "http://127.0.0.1:3333/git" }

[registry]
default = "my-registry"

[net]
git-fetch-with-cli = true

[source.crates-io]
registry = 'https://github.com/rust-lang/crates.io-index'
replace-with = 'local-registry'

[source.local-registry]
local-registry = '/home/codespace/vendor'
```

when we then try to publish crate C it fails due to it not locating the two crates A and B in the index.

We should follow suit with `cargo-local-registry` so as to also make the file structure clean. Having .crate files and various indexes in same folder won't look clean and becomes hard to navigate.
Do indicate if I’m missing anything. Thanks.

**Comment by d-e-s-o** [comment]
Unfortunately, your explanation does not allow me to follow your argument. With `index/` being a symlink to the registry root, files would be opened as they were before. Can you please provide a working script showcasing the issue you are seeing?

> `cargo-local-registry` stores all indexes in the index path which we should follow suit so that its config can work for us

Let me clarify two things (and no offense meant). First of all, I don't really care about `cargo-local-registry`. It does not define some kind of standard that we should implement nor does it constitute any crucial component that we should strive to be interoperable with. While the maintainer seems responsive, the crate itself hasn't seen an update in more than a year, with at least one core dependency (`cargo`) having advanced by twelve or so minor versions without `cargo-local-registry` attempting to catch up; arguably suggesting no real interest of maintenance and rendering it even less relevant in my eyes. The use case you describe [here](https://github.com/d-e-s-o/cargo-http-registry/issues/2#issuecomment-913550359) makes somewhat sense to me and I am not fundamentally opposed to supporting it. Whether the directory layout is subjectively "clean" or easy to navigate, for me, is a miniscule concern at best. It is an implementation detail that I don't see users of this crate caring about.
Second, there are hard [technical reasons](https://github.com/d-e-s-o/cargo-http-registry/commit/9feff784cc27c60c4bd199a484727b74eceda20f) why the proposed layout does not work. If it does not work the crate is no longer usable for the purpose it was built. At this point the discussion is over. Either we find an alternative (which I proposed) or we roll back. Now I don't believe that those technical reasons are insurmountable (from what I understand `git` supports a mode in which the repository resides outside of the directory whose files are being tracked, and which may be usable here; I'd be happy to dig out pointers on request), but I don't have the time or interest in following down that road myself.

So from my perspective it's either a backout of the offending change (which would break your use case and get us back to square one), the symlink approach (which I am yet to be convinced does not work), or any other concrete technical solution that gets the registry back into working state (which I'd be happy to accept if implemented properly but won't spend time on myself), but points about what we should do without a clear technical path to getting there are not really helpful at this point.

**Comment by metaclips** [comment]
Valid reasons @d-e-s-o, if we could make this program a standalone whereby `cargo-http-registry` can also import crates fro m crates.io to its cache, I really don't see a need for `cargo-local-registry`. Also, paths/location of files are of no bother really, having a fully fledged cargo server and retriever is really the motive here.

So I took more time to checkout the symlink implementation and here's what I found out

I got the `symlink` implementation to `cargo publish` successfully, repository [here](https://github.com/metaclips/Registry). 
There seem to be a weird layout in how the symlinks are created see below
<img width="746" alt="Screenshot 2021-09-09 at 9 48 35 PM" src="https://user-images.githubusercontent.com/31141573/132760425-4a67abae-265c-43f3-9a99-233c44751b6a.png">

Same script in [repository](https://github.com/metaclips/Registry) also publishes successfully and I can retrieve it too for bar crate when we use the changes we made originally using checkout 4fd8d767f8b814ed382c465216b9477cb2fbfbf9. Can be changed in https://github.com/metaclips/Registry/blob/e503d5eae17d9e5893c363598c0e737891e0c9c4/.sh#L13. 

Do indicate if I'm off track 😁

**Comment by d-e-s-o** [comment]
Hm, interesting. I don't think you are off track. The script does run through for me (though I had to make a few small adjustments):
```
$ bash .sh
mkdir: cannot create directory ‘.cargo’: File exists
mkdir: cannot create directory ‘vendor’: File exists
Retrieved dependencies from crates.io
    Updating `http://127.0.0.1:3333/git` index
warning: manifest has no description, license, license-file, documentation, homepage or repository.
See https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata for more info.
   Packaging foo v0.1.0 (/home/deso/local/src/rust/cargo-http-registry/Registry/foo)
   Verifying foo v0.1.0 (/home/deso/local/src/rust/cargo-http-registry/Registry/foo)
   Compiling foo v0.1.0 (/tmp/rust-build-artifacts/home/deso/local/src/rust/cargo-http-registry/Registry/foo/target/package/foo-0.1.0)
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
   Uploading foo v0.1.0 (/home/deso/local/src/rust/cargo-http-registry/Registry/foo)
add this to your .cargo/config somewhere:

    [source.crates-io]
    registry = 'https://github.com/rust-lang/crates.io-index'
    replace-with = 'local-registry'

    [source.local-registry]
    local-registry = '/home/deso/local/src/rust/cargo-http-registry/Registry/bar/../vendor'


    Updating `http://127.0.0.1:3333/git` index
warning: manifest has no description, license, license-file, documentation, homepage or repository.
See https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata for more info.
   Packaging bar v0.1.0 (/home/deso/local/src/rust/cargo-http-registry/Registry/bar)
   Verifying bar v0.1.0 (/home/deso/local/src/rust/cargo-http-registry/Registry/bar)
   Unpacking foo v0.1.0 (registry `/home/deso/local/src/rust/cargo-http-registry/Registry/foo/../vendor`)
   Compiling proc-macro2 v1.0.29
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.76
   Compiling quote v1.0.9
   Compiling thiserror-impl v1.0.29
   Compiling thiserror v1.0.29
   Compiling foo v0.1.0
   Compiling bar v0.1.0 (/tmp/rust-build-artifacts/home/deso/local/src/rust/cargo-http-registry/Registry/bar/target/package/bar-0.1.0)
    Finished dev [unoptimized + debuginfo] target(s) in 4.48s
   Uploading bar v0.1.0 (/home/deso/local/src/rust/cargo-http-registry/Registry/bar)
```

Afterwards, the `vendor/` directory looks like this:
```
$ tree vendor/
vendor/
├── 3
│   ├── b
│   │   └── bar
│   ├── f
│   │   └── foo
│   └── s
│       └── syn
├── bar-0.1.0.crate
├── config.json
├── foo-0.1.0.crate
├── index -> .
├── pr
│   └── oc
│       └── proc-macro2
├── proc-macro2-1.0.29.crate
├── qu
│   └── ot
│       └── quote
├── quote-1.0.9.crate
├── syn-1.0.76.crate
├── th
│   └── is
│       ├── thiserror
│       └── thiserror-impl
├── thiserror-1.0.29.crate
├── thiserror-impl-1.0.29.crate
├── un
│   └── ic
│       └── unicode-xid
└── unicode-xid-0.2.2.crate

13 directories, 17 files
```

So there is nothing weird on my side. Could this just be a display issue? After all, that's a recursive symlink if you will. I assume you are on Linux and not just in some emulated environment on a Windows host or some such, correct?

**Comment by d-e-s-o** [comment]
The more I think about...I think it is just the way your file manager displays the tree. Try using `tree` or just `ls -R` and see if it looks better.

**Comment by metaclips** [comment]
Ha, will do that. Were you able to run it against the recent change we made @d-e-s-o ?

**Comment by d-e-s-o** [comment]
> Ha, will do that. Were you able to run it against the recent change we made @d-e-s-o ?

I don't think it has any relevance, to be honest. It's just not what the change breaks. I added tests in the stack that verify that everything is functioning correctly and they don't work with https://github.com/d-e-s-o/cargo-http-registry/commit/eed5900f79083c1ddf7cba8a4a01169c85f26a38.

**Comment by d-e-s-o** [comment]
So are we good here now? I'd want to wrap this up.

**Comment by metaclips** [comment]
> So are we good here now? I'd want to wrap this up.

Sure. I can always create another issue if I have any question or find any bugs.
Also, can you please direct me to the test that fails?

**Comment by d-e-s-o** [comment]
Sounds good.

> Also, can you please direct me to the test that fails?

https://github.com/d-e-s-o/cargo-http-registry/blob/98a740eb38521fc73a5c009d600116f73a5fa6f4/tests/end-to-end.rs#L228
