### ISSUE TITLE
Create Dockerfile and publish docker image

### ISSUE THREAD

**Issue by marcoieni** [d-e-s-o/cargo-http-registry#5]
Hi 👋 
I wanted a cargo registry for testing purposes, and this crate worked for me. Thanks!

Now I want to integrate this project into my test suite.
The easiest way for me would be via a docker image.
Are you willing to create a Dockerfile and publish it either to the GitHub registry or to the DockerHub?
If you want, I can open a PR and create a [Dockerfile](https://github.com/MarcoIeni/release-plz/blob/main/Dockerfile) and a [CD pipeline](https://github.com/MarcoIeni/release-plz/blob/main/.github/workflows/docker.yml) similar to what I have in [release-plz](https://github.com/MarcoIeni/release-plz).

**Comment by d-e-s-o** [comment]
I don't really have any use for Docker and the eco system surrounding it. Can you create a Dockerfile yourself and publish it? I don't see why it needs to happen from this project itself, to be honest.

**Comment by marcoieni** [comment]
Ok, no problem, thanks 👍

**Comment by marcoieni** [comment]
[Here](https://github.com/MarcoIeni/cargo-http-registry/pkgs/container/cargo-http-registry) I maintain a fork of this project where I push the docker image to the ghcr.io registry. 👍
