### ISSUE TITLE
Add support for `/api/v1/crates/{}/versions`

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [d-e-s-o/cargo-http-registry#62]

**Comment by d-e-s-o** [comment]
Unactionable without any kind of reference...

**Comment by StackOverflowExcept1on** [comment]
I would like `cargo-http-registry` repository to have support for the `/api/v1/crates/{}/versions` route.
https://github.com/gear-tech/gear/blob/0f7d727ccbba6135acba018d15648161e2ea7e3f/utils/crates-io/src/version.rs#L37

**Comment by d-e-s-o** [comment]
Seems to be `crates.io` specific. It's not documented anywhere from what I can tell.
