### ISSUE TITLE
Consider committing Cargo.lock for reproducibility

### ISSUE THREAD

**Issue by marcoieni** [d-e-s-o/cargo-http-registry#8]
The Cargo book suggest to commit `Cargo.lock` for binaries. See [this](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries).

**Comment by d-e-s-o** [comment]
Right; why is it necessary for you, though? It ends up just being a bunch of maintenance effort without any obvious benefit. It's not like I am shipping binaries that would need to be reproducible. Users can always use their own lock files. What is your use case? The Docker image?

**Comment by marcoieni** [comment]
> why is it necessary for you, though?

Without the `Cargo.lock` file my docker pipeline didn't work.
I committed the `Cargo.lock` in my fork, so it's not necessary for me anymore.
It would be nice if the `Cargo.lock` file was maintained here instead of my fork.
But if that's too much maintenance effort, feel free to close this issue 👍

**Comment by d-e-s-o** [comment]
Makes sense. I think what we can do is integrate your additions back here, if that's alright with you. Then there would be a reason to check-in `Cargo.lock` and I could set up Dependabot for dependency management, perhaps. I wasn't aware that there is a GitHub container registry (which simplifies account management etc.) and while I don't use Docker myself, there is some value in having such an image available directly (and it does not look terribly complicated to create the image every release or so).

**Comment by marcoieni** [comment]
> I think what we can do is integrate your additions back here

Yes, absolutely! I opened #9

**Comment by d-e-s-o** [comment]
Done with https://github.com/d-e-s-o/cargo-http-registry/commit/bfee06cd9506de75b12060219b15af5258a2f6a7
